name: easy_story_flutter
description: Flutter Architecture inspired by Domain Driven Design, Onion and Clean Architecture.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  http: ^0.13.5
  shared_preferences: ^2.0.15
  enum_to_string: ^2.0.1
  fancy_bottom_navigation: ^0.3.3
  flutter_html: ^2.2.1
  flutter_gherkin: ^2.0.0
  glob: ^2.1.0
  flutter_color: ^2.0.0
  flutter_quill: ^4.2.3
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  image_picker: ^0.8.6


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
 
